// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdn-6gOYTI-HW7DMe__FYhXGheIOLGrNA',
    appId: '1:308195757527:web:c1c7099ff48e3464b20f92',
    messagingSenderId: '308195757527',
    projectId: 'btack-250c1',
    authDomain: 'btack-250c1.firebaseapp.com',
    storageBucket: 'btack-250c1.firebasestorage.app',
    measurementId: 'G-KC255L5BQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNQqp7McxKvNoMAIFOlkjd8EuVmXuAYk',
    appId: '1:308195757527:android:4f377ed078414ee5b20f92',
    messagingSenderId: '308195757527',
    projectId: 'btack-250c1',
    storageBucket: 'btack-250c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Jf7DQjJ8SwYMWUhjEicnP5wQRZr-zg8',
    appId: '1:308195757527:ios:42d31b7b4ac85787b20f92',
    messagingSenderId: '308195757527',
    projectId: 'btack-250c1',
    storageBucket: 'btack-250c1.firebasestorage.app',
    iosBundleId: 'com.example.thuChiCaNhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Jf7DQjJ8SwYMWUhjEicnP5wQRZr-zg8',
    appId: '1:308195757527:ios:42d31b7b4ac85787b20f92',
    messagingSenderId: '308195757527',
    projectId: 'btack-250c1',
    storageBucket: 'btack-250c1.firebasestorage.app',
    iosBundleId: 'com.example.thuChiCaNhan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdn-6gOYTI-HW7DMe__FYhXGheIOLGrNA',
    appId: '1:308195757527:web:27aec5f08fccc4f9b20f92',
    messagingSenderId: '308195757527',
    projectId: 'btack-250c1',
    authDomain: 'btack-250c1.firebaseapp.com',
    storageBucket: 'btack-250c1.firebasestorage.app',
    measurementId: 'G-JC37JRJ6J3',
  );
}
